### ISSUE TITLE
Footer improvements 

### ISSUE THREAD

**Issue by jeancflanagan** [opattison/olivermakes#328]
- Consider using progressive disclosure for copyright details.
- Consider having a list of links for e.g. source code, pattern library, RSS, and twitter — with less explanatory prose.

**Comment by opattison** [comment]
Not using the progressive disclosure pattern, but using a new visual style for those items:

<img width="860" alt="2016-10-06 21 48 27" src="https://cloud.githubusercontent.com/assets/885300/19176533/b0bc8102-8c0e-11e6-9589-f73ed3b07361.png">

**Comment by opattison** [comment]
I’m not sure about the “work with” icon. I am using the Git icon at the moment as a stand-in and I actually like it, but it may not work.
